version: 0
allowPullRequests: public
metadata:
  name: Basket
  description: Basket CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  # build the docker image
  - metadata:
      name: Basket Docker Image Creation
      description: Basket Docker Image Creation
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    routes:
      - "notify.irc-channel.#basket.on-any"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - push
          - release
    payload:
      maxRunTime: 1800
      image: "docker:17-git"
      env:
        DOCKER_IMAGE_TAG: "mozmeao/basket:{{ event.head.sha }}"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/sh"
        - "-c"
        - >-
          git clone $GITHUB_HEAD_REPO_URL basket && cd basket && git checkout $GITHUB_HEAD_BRANCH &&
          docker build -t "$DOCKER_IMAGE_TAG" --pull=true . &&
          docker run --env-file docker/envfiles/test.env "$DOCKER_IMAGE_TAG" bin/run-tests.sh
