sudo: required
services:
  - docker
language: python
env:
  global:
    # Deis
    - DEIS_DEV_APPLICATION=basket-dev
    - DEIS_STAGE_APPLICATION=basket-stage
    - DEIS_PROD_APPLICATION=basket-prod
    - DEIS_USERNAME=travis
    # Docker
    - DOCKER_REPOSITORY=mozorg/basket
    - DOCKER_EMAIL=foo@example.com
    - DOCKER_USERNAME=mozjenkins
    # MySQL
    - MYSQL_DATABASE=basket
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    # Django
    - SECRET_KEY=ssssssssshhhhhhhhhhhhh
    - SUPERTOKEN=im-super-thanks-for-asking
    - DEBUG=False
    - ALLOWED_HOSTS=*
    - CELERY_ALWAYS_EAGER=True
    - DATABASE_URL=mysql://root@db/basket
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
  - export DOCKER_IMAGE_TAG="${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}"
install:
  # Take advantage of docker caching by pulling previously built images.
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull $DOCKER_IMAGE_TAG || true
  - docker build -t $DOCKER_IMAGE_TAG --pull=true .
before_script:
  - env > .env
script:
  - docker run $DOCKER_IMAGE_TAG flake8 news
  - docker run -d --name mysql -e MYSQL_DATABASE -e MYSQL_ALLOW_EMPTY_PASSWORD mysql:5.6
  # block until mysql is ready
  - docker run --link mysql:db -e CHECK_PORT=3306 -e CHECK_HOST=db giorgos/takis
  - docker run --env-file .env --link mysql:db $DOCKER_IMAGE_TAG bash -c "./manage.py migrate --noinput && py.test news"
notifications:
  irc:
    channels:
      - irc.mozilla.org#basket
    on_success: change
    on_failure: always
    use_notice: true
deploy:
  - provider: script
    script: bin/deploy-travis.sh $DEIS_DEV_APPLICATION
    on:
      branch: master
      repo: mozilla/basket
  - provider: script
    script: bin/deploy-travis.sh $DEIS_STAGE_APPLICATION
    on:
      branch: master
      repo: mozilla/basket
  - provider: script
    script: bin/deploy-travis.sh $DEIS_PROD_APPLICATION
    on:
      tags: true
      repo: mozilla/basket
