version: "3.4"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=basket

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: basket
      POSTGRES_USER: basket
      POSTGRES_PASSWORD: basket
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 10

  pgloader:
    image: dimitri/pgloader:latest
    depends_on:
      - db
      - postgres
    command:
      pgloader --verbose mysql://root@db/basket postgresql://basket:basket@postgres/basket

  redis:
    image: redis
    platform: linux/amd64

  web:
    build:
      context: .
      args:
        GIT_SHA: ${GIT_COMMIT:-latest}
    image: mozmeao/basket:${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64
    volumes:
      - .:/app
    env_file:
      - docker/envfiles/local.env
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - postgres
      - redis
    command:
      ./bin/run-dev.sh

  worker:
    image: mozmeao/basket:${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - docker/envfiles/local.env
      - .env
    depends_on:
      - db
      - postgres
      - redis
    command:
      ./bin/run-worker.sh

  test:
    image: mozmeao/basket:${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64
    volumes:
      - .:/app
    env_file:
      - docker/envfiles/local.env
      - docker/envfiles/test.env
    depends_on:
      - db
      - postgres
      - redis
    command:
      ./bin/run-tests.sh

  test-image:
    image: mozmeao/basket:${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64
    env_file:
      - docker/envfiles/local.env
      - docker/envfiles/test.env
    depends_on:
      - db
      - postgres
      - redis
    command:
      ./bin/run-tests.sh

  builder:
    build:
      context: .
      target: builder
    image: mozmeao/basket:builder-${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64

  compile-requirements:
    image: mozmeao/basket:builder-${GIT_COMMIT_SHORT:-latest}
    platform: linux/amd64
    command:
      ./bin/compile-requirements.sh
    volumes:
      - .:/app
